config/routes.rb
Rails.application.routes.draw do

  resources :crkpuramdata
  resources :crkpdata
  resources :crkpurams
  root to: "photos#index"
  resources :photos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crkpdatum.rb
class Crkpdatum < ApplicationRecord
end

app/models/crkpuram.rb
class Crkpuram < ApplicationRecord
end

app/models/crkpuramdatum.rb
class Crkpuramdatum < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
	#Mounts paperclip image
  has_attached_file :image
  validates_attachment_content_type :image, :content_type =>
  	["image/jpg", "image/jpeg", "image/png", "image/gif"], size: { in: 0..100.kilobytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crkpdata_controller.rb
class CrkpdataController < ApplicationController
  before_action :set_crkpdatum, only: [:show, :edit, :update, :destroy]

  # GET /crkpdata
  # GET /crkpdata.json
  def index
    @crkpdata = Crkpdatum.all
  end

  # GET /crkpdata/1
  # GET /crkpdata/1.json
  def show
  end

  # GET /crkpdata/new
  def new
    @crkpdatum = Crkpdatum.new
  end

  # GET /crkpdata/1/edit
  def edit
  end

  # POST /crkpdata
  # POST /crkpdata.json
  def create
    @crkpdatum = Crkpdatum.new(crkpdatum_params)

    respond_to do |format|
      if @crkpdatum.save
        format.html { redirect_to @crkpdatum, notice: 'Crkpdatum was successfully created.' }
        format.json { render :show, status: :created, location: @crkpdatum }
      else
        format.html { render :new }
        format.json { render json: @crkpdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crkpdata/1
  # PATCH/PUT /crkpdata/1.json
  def update
    respond_to do |format|
      if @crkpdatum.update(crkpdatum_params)
        format.html { redirect_to @crkpdatum, notice: 'Crkpdatum was successfully updated.' }
        format.json { render :show, status: :ok, location: @crkpdatum }
      else
        format.html { render :edit }
        format.json { render json: @crkpdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crkpdata/1
  # DELETE /crkpdata/1.json
  def destroy
    @crkpdatum.destroy
    respond_to do |format|
      format.html { redirect_to crkpdata_url, notice: 'Crkpdatum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crkpdatum
      @crkpdatum = Crkpdatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crkpdatum_params
      params.require(:crkpdatum).permit(:name, :adhar, :mobile)
    end
end

app/controllers/crkpuramdata_controller.rb
class CrkpuramdataController < ApplicationController
  before_action :set_crkpuramdatum, only: [:show, :edit, :update, :destroy]

  # GET /crkpuramdata
  # GET /crkpuramdata.json
  def index
    @crkpuramdata = Crkpuramdatum.all
  end

  # GET /crkpuramdata/1
  # GET /crkpuramdata/1.json
  def show
  end

  # GET /crkpuramdata/new
  def new
    @crkpuramdatum = Crkpuramdatum.new
  end

  # GET /crkpuramdata/1/edit
  def edit
  end

  # POST /crkpuramdata
  # POST /crkpuramdata.json
  def create
    @crkpuramdatum = Crkpuramdatum.new(crkpuramdatum_params)

    respond_to do |format|
      if @crkpuramdatum.save
        format.html { redirect_to @crkpuramdatum, notice: 'Crkpuramdatum was successfully created.' }
        format.json { render :show, status: :created, location: @crkpuramdatum }
      else
        format.html { render :new }
        format.json { render json: @crkpuramdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crkpuramdata/1
  # PATCH/PUT /crkpuramdata/1.json
  def update
    respond_to do |format|
      if @crkpuramdatum.update(crkpuramdatum_params)
        format.html { redirect_to @crkpuramdatum, notice: 'Crkpuramdatum was successfully updated.' }
        format.json { render :show, status: :ok, location: @crkpuramdatum }
      else
        format.html { render :edit }
        format.json { render json: @crkpuramdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crkpuramdata/1
  # DELETE /crkpuramdata/1.json
  def destroy
    @crkpuramdatum.destroy
    respond_to do |format|
      format.html { redirect_to crkpuramdata_url, notice: 'Crkpuramdatum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crkpuramdatum
      @crkpuramdatum = Crkpuramdatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crkpuramdatum_params
      params.require(:crkpuramdatum).permit(:full_name, :care_of, :adhar, :mobile, :bank_name, :ifsccode, :account_number)
    end
end

app/controllers/crkpurams_controller.rb
class CrkpuramsController < ApplicationController
  before_action :set_crkpuram, only: [:show, :edit, :update, :destroy]

  # GET /crkpurams
  # GET /crkpurams.json
  def index
    @crkpurams = Crkpuram.all
  end

  # GET /crkpurams/1
  # GET /crkpurams/1.json
  def show
  end

  # GET /crkpurams/new
  def new
    @crkpuram = Crkpuram.new
  end

  # GET /crkpurams/1/edit
  def edit
  end

  # POST /crkpurams
  # POST /crkpurams.json
  def create
    @crkpuram = Crkpuram.new(crkpuram_params)

    respond_to do |format|
      if @crkpuram.save
        format.html { redirect_to @crkpuram, notice: 'Crkpuram was successfully created.' }
        format.json { render :show, status: :created, location: @crkpuram }
      else
        format.html { render :new }
        format.json { render json: @crkpuram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crkpurams/1
  # PATCH/PUT /crkpurams/1.json
  def update
    respond_to do |format|
      if @crkpuram.update(crkpuram_params)
        format.html { redirect_to @crkpuram, notice: 'Crkpuram was successfully updated.' }
        format.json { render :show, status: :ok, location: @crkpuram }
      else
        format.html { render :edit }
        format.json { render json: @crkpuram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crkpurams/1
  # DELETE /crkpurams/1.json
  def destroy
    @crkpuram.destroy
    respond_to do |format|
      format.html { redirect_to crkpurams_url, notice: 'Crkpuram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crkpuram
      @crkpuram = Crkpuram.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crkpuram_params
      params.fetch(:crkpuram, {})
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

def index
  @photos = Photo.order('created_at')
 end

 #New action for creating a new photo
 def new
  @photo = Photo.new
 end

 #Create action ensures that submitted photo gets created if it meets the requirements
 def create
  @photo = Photo.new(photo_params)
  if @photo.save
   flash[:notice] = "Successfully added new photo!"
   redirect_to root_path
  else
   flash[:alert] = "Error adding new photo!"
   render :new
  end
 end

 def destroy
  @photo = Photo.find(params[:id])
    if @photo.destroy
      flash[:notice] = "Successfully deleted photo!"
      redirect_to root_path
    else
      flash[:alert] = "Error deleting photo!"
    end
  end

 private

 #Permitted parameters when creating a photo. This is used for security reasons.
 def photo_params
  params.require(:photo).permit(:title, :image)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crkpdata_helper.rb
module CrkpdataHelper
end

app/helpers/crkpuramdata_helper.rb
module CrkpuramdataHelper
end

app/helpers/crkpurams_helper.rb
module CrkpuramsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/crkpdata/_form.html.erb
<%= form_for(crkpdatum) do |f| %>
  <% if crkpdatum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crkpdatum.errors.count, "error") %> prohibited this crkpdatum from being saved:</h2>

      <ul>
      <% crkpdatum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :adhar %>
    <%= f.text_field :adhar %>
  </div>

  <div class="field">
    <%= f.label :mobile %>
    <%= f.text_field :mobile %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crkpdata/edit.html.erb
<h1>Editing Crkpdatum</h1>

<%= render 'form', crkpdatum: @crkpdatum %>

<%= link_to 'Show', @crkpdatum %> |
<%= link_to 'Back', crkpdata_path %>

app/views/crkpdata/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crkpdata</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adhar</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crkpdata.each do |crkpdatum| %>
      <tr>
        <td><%= crkpdatum.name %></td>
        <td><%= crkpdatum.adhar %></td>
        <td><%= crkpdatum.mobile %></td>
        <td><%= link_to 'Show', crkpdatum %></td>
        <td><%= link_to 'Edit', edit_crkpdatum_path(crkpdatum) %></td>
        <td><%= link_to 'Destroy', crkpdatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crkpdatum', new_crkpdatum_path %>

app/views/crkpdata/new.html.erb
<h1>New Crkpdatum</h1>

<%= render 'form', crkpdatum: @crkpdatum %>

<%= link_to 'Back', crkpdata_path %>

app/views/crkpdata/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crkpdatum.name %>
</p>

<p>
  <strong>Adhar:</strong>
  <%= @crkpdatum.adhar %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @crkpdatum.mobile %>
</p>

<%= link_to 'Edit', edit_crkpdatum_path(@crkpdatum) %> |
<%= link_to 'Back', crkpdata_path %>

app/views/crkpuramdata/_form.html.erb
<%= form_for(crkpuramdatum) do |f| %>
  <% if crkpuramdatum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crkpuramdatum.errors.count, "error") %> prohibited this crkpuramdatum from being saved:</h2>

      <ul>
      <% crkpuramdatum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>

  <div class="field">
    <%= f.label :care_of %>
    <%= f.text_field :care_of %>
  </div>

  <div class="field">
    <%= f.label :adhar %>
    <%= f.text_field :adhar %>
  </div>

  <div class="field">
    <%= f.label :mobile %>
    <%= f.text_field :mobile %>
  </div>

  <div class="field">
    <%= f.label :bank_name %>
    <%= f.text_field :bank_name %>
  </div>

  <div class="field">
    <%= f.label :ifsccode %>
    <%= f.text_field :ifsccode %>
  </div>

  <div class="field">
    <%= f.label :account_number %>
    <%= f.text_field :account_number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crkpuramdata/edit.html.erb
<h1>Editing Crkpuramdatum</h1>

<%= render 'form', crkpuramdatum: @crkpuramdatum %>

<%= link_to 'Show', @crkpuramdatum %> |
<%= link_to 'Back', crkpuramdata_path %>

app/views/crkpuramdata/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crkpuramdata</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Care of</th>
      <th>Adhar</th>
      <th>Mobile</th>
      <th>Bank name</th>
      <th>Ifsccode</th>
      <th>Account number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crkpuramdata.each do |crkpuramdatum| %>
      <tr>
        <td><%= crkpuramdatum.full_name %></td>
        <td><%= crkpuramdatum.care_of %></td>
        <td><%= crkpuramdatum.adhar %></td>
        <td><%= crkpuramdatum.mobile %></td>
        <td><%= crkpuramdatum.bank_name %></td>
        <td><%= crkpuramdatum.ifsccode %></td>
        <td><%= crkpuramdatum.account_number %></td>
        <td><%= link_to 'Show', crkpuramdatum %></td>
        <td><%= link_to 'Edit', edit_crkpuramdatum_path(crkpuramdatum) %></td>
        <td><%= link_to 'Destroy', crkpuramdatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crkpuramdatum', new_crkpuramdatum_path %>

app/views/crkpuramdata/new.html.erb
<h1>New Crkpuramdatum</h1>

<%= render 'form', crkpuramdatum: @crkpuramdatum %>

<%= link_to 'Back', crkpuramdata_path %>

app/views/crkpuramdata/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @crkpuramdatum.full_name %>
</p>

<p>
  <strong>Care of:</strong>
  <%= @crkpuramdatum.care_of %>
</p>

<p>
  <strong>Adhar:</strong>
  <%= @crkpuramdatum.adhar %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @crkpuramdatum.mobile %>
</p>

<p>
  <strong>Bank name:</strong>
  <%= @crkpuramdatum.bank_name %>
</p>

<p>
  <strong>Ifsccode:</strong>
  <%= @crkpuramdatum.ifsccode %>
</p>

<p>
  <strong>Account number:</strong>
  <%= @crkpuramdatum.account_number %>
</p>

<%= link_to 'Edit', edit_crkpuramdatum_path(@crkpuramdatum) %> |
<%= link_to 'Back', crkpuramdata_path %>

app/views/crkpurams/_form.html.erb
<%= form_for(crkpuram) do |f| %>
  <% if crkpuram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crkpuram.errors.count, "error") %> prohibited this crkpuram from being saved:</h2>

      <ul>
      <% crkpuram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crkpurams/edit.html.erb
<h1>Editing Crkpuram</h1>

<%= render 'form', crkpuram: @crkpuram %>

<%= link_to 'Show', @crkpuram %> |
<%= link_to 'Back', crkpurams_path %>

app/views/crkpurams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crkpurams</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crkpurams.each do |crkpuram| %>
      <tr>
        <td><%= link_to 'Show', crkpuram %></td>
        <td><%= link_to 'Edit', edit_crkpuram_path(crkpuram) %></td>
        <td><%= link_to 'Destroy', crkpuram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crkpuram', new_crkpuram_path %>

app/views/crkpurams/new.html.erb
<h1>New Crkpuram</h1>

<%= render 'form', crkpuram: @crkpuram %>

<%= link_to 'Back', crkpurams_path %>

app/views/crkpurams/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_crkpuram_path(@crkpuram) %> |
<%= link_to 'Back', crkpurams_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ClipUploader</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Upload New Image', new_photo_path %></li>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Image Upload</title>

  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Renders navigation file located at app/views/layouts/_navigation.html.erb -->
    <%= render "layouts/navigation" %>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/index.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<div class="media">
  <% @photos.each do |photo| %>
    <div class="media-left">
      <!-- Renders image -->
      <%= photo.title %>
      <%= link_to image_tag(photo.image.url, class: 'media-object', :size => "260x180"), photo.image.url, target: '_blank' %>
      <%= photo.image_file_name %></br>
      <%= link_to 'Remove', photo_path(photo), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>    
    </div>
    
    <div class="media-body">
      <h4 class="media-heading"><%= photo.title %></h4>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<%= form_for @photo, html: { multipart: true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
      </h2>
      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
        <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
    </div>
<% end %>